name: Deploy to GCP

on:
  push:
    branches:
      - master 
    
  pull_request:
    branches:
      - master
    paths:
      - Dockerfile.prod
      - requirements.txt
      - .github/workflows/deploy-to-gcp.yml
      - */**/*.py
      - */**/*.yaml

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run linting and tests
        run: |
          # Add linting
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # Add test commands here
          # pytest tests/ -v

      # Set up GCP authentication
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      # Configure Docker to use the gcloud command-line tool
      - name: Configure Docker for GCR
        run: gcloud auth configure-docker

      # Build and push Docker image using production Dockerfile
      - name: Build and Push Docker image
        run: |
          # Set image name with timestamp for versioning
          IMAGE_NAME=gcr.io/${{ secrets.GCP_PROJECT_ID }}/mqtt-streamer-senelec-keurgorgui:${{ github.sha }}

          # Build the Docker image using the production Dockerfile
          docker build -f Dockerfile.prod -t $IMAGE_NAME .

          # Push the Docker image to Google Container Registry
          docker push $IMAGE_NAME

          # Also tag as latest
          docker tag $IMAGE_NAME gcr.io/${{ secrets.GCP_PROJECT_ID }}/mqtt-streamer-senelec-keurgorgui:latest
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/mqtt-streamer-senelec-keurgorgui:latest

          # Store the image name for later use
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      # Deploy to GCP compute instance
      - name: Deploy to VM instance
        run: |
          # Generate a deployment script
          cat > deploy.sh << 'EOF'
          #!/bin/bash

          # Pull the latest image
          docker pull ${IMAGE_NAME}

          # Stop and remove existing container if it exists
          docker stop mqtt-streamer-senelec-keurgorgui || true
          docker rm mqtt-streamer-senelec-keurgorgui || true

          # Run the new container
          docker run -d \
            --name mqtt-streamer-senelec-keurgorgui \
            --restart always \
            -p 8000:8000 \
            -v /etc/mqtt-streamer/config:/app/config \
            -v /etc/mqtt-streamer/certs:/app/certs \
            -v /var/log/mqtt-streamer:/app/logs \
            --env-file /etc/mqtt-streamer/.env \
            ${IMAGE_NAME}

          # Check if the container started successfully
          sleep 5
          if [ "$(docker ps -q -f name=mqtt-streamer-senelec-keurgorgui)" ]; then
            echo "Deployment successful. Container is running."
            docker logs mqtt-streamer-senelec-keurgorgui --tail 20
          else
            echo "Deployment failed. Container is not running."
            docker logs mqtt-streamer-senelec-keurgorgui
            exit 1
          fi

          # Cleanup old images
          docker image prune -a -f --filter "until=24h"
          EOF

          # Copy the deployment script to the instance
          gcloud compute scp deploy.sh ${{ secrets.GCP_INSTANCE_NAME }}:~ --zone ${{ secrets.GCP_ZONE }}

          # Set the IMAGE_NAME environment variable and execute the script
          gcloud compute ssh ${{ secrets.GCP_INSTANCE_NAME }} --zone ${{ secrets.GCP_ZONE }} \
            --command "chmod +x ~/deploy.sh && IMAGE_NAME=$IMAGE_NAME ~/deploy.sh"

      # Notify on success
      - name: Notify on successful deployment
        run: |
          echo "Successfully deployed to GCP instance ${{ secrets.GCP_INSTANCE_NAME }}"
          echo "Application is running at http://${{ secrets.GCP_INSTANCE_IP }}:8000"
